substitutions:
  _REGION: "us-central1"
  _REPO:   "recs-api
  _IMAGE:  "recs-api"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["tag",
           "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA",
           "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
